In [ ]:
import numpy as np
# 대괄호를 이용해 행렬을 만든다.
a = np.matrix( [ [1,2], [3,4] ])

# 작은 따옴표를 사용해 다음과 같이 만들 수도 있다.
a = np.matrix( '1 2; 3 4' )

# +, -, *, / 연산자를 사용해 행렬 덧셈, 뺄셈, 곱셈, 나눗셈 연산을 한다
ap = a + a  # 행렬 간 원소끼리 더한다.
am = a - a  # 행렬 간 원소끼리 뺀다.
aa = a * a  # 행렬 곱셈을 한다.
ad = a / a  # 행렬 간 원소끼리 나눈다.

# matrix.T 함수를 사용해 전치행렬을 구한다.
aT = a.T

# matrix.I 함수를 사용해 역행렬을 구한다.
aI = a.I

# 콜론(:)은 행렬의 행이나 열 전체를 의미한다.
# 행이나 열의 인덱스는 0부터 시작한다.
# 행렬[ 행, 열 ] 같은 방식으로 행렬의 일부를 지정할 수 있다.
row0 = a[0, :]  # 첫 번째 행의 모든 열의 값, 즉 첫 번째 행 전체를 구한다
row1 = a[1, :]  # 두 번째 행의 모든 열의 값, 즉 두 번째 행 전체를 구한다.
col0 = a[:, 0]  # 첫 번째 열의 모든 행의 값, 즉 첫 번째 열 전체를 구한다.
col1 = a[:, 1]  # 두 번째 열의 모든 행의 값, 즉 두 번째 열 전체를 구한다.

# numpy 라이브러리를 np라는 이름으로 임포트한다.
import numpy as np

# numpy의 matrix 클래스를 사용해 국면별 확률을 1*3 행렬로 만든다.
prob = np.matrix([ [1/3, 1/3, 1/3] ])

# 주식 A와 B의 수익률을 1*3 행렬로 만든다.
stock_a = np.matrix( [ [7, 4, 1] ] )
stock_b = np.matrix( [ [13, 4, -5] ] )

# 행렬 곱하기 연산을 수행한다. 단, 행렬의 차원이 맞아야 하므로
# stock_a.T, stock_b.T와 같이 stock_a와 stock_b 행렬을 전치(행과
# 열의 방향을 바꾸는 것) 시켜준다. 따라서 prob는 1*3, stock_a와 
# stock_b는 3*1 행렬이 돼 곱하기 연산의 결과 1*1의 결과 행렬이 
# 나오게 된다.
ex_a = prob * stock_a.T
ex_b = prob * stock_b.T

# %.2f는 %로 연결한 변수(% ex_a와 % ex_b)의 서식을 지정하는 것으로, 
# 소수점 이하 두 자리 실수(f)로 출력한다. f 뒤 %%는 백분율 표시 %를
# 붙이기 위한 것이다.
print( '주식 A의 기대수익률은 %.2f%%' % ex_a )
print( '주식 B의 기대수익률은 %.2f%%' % ex_b )

# 개별 주식의 기대수익률을 계산했으므로 두 개 주식으로 구성된 포트폴리오
# 의 기대수익률을 계산할 차례다.
# weight는 투자 비중을 가리키는 1*2 행렬이다.
weight = np.matrix( [ [ 0.5, 0.5] ] )

# '투자 비중 * 주식 기대수익률'이라는 행렬 연산을 위해 앞서 구한 각 주식
# 의 기대수익률을 1*2 행렬로 만든다. 그런데 ex_a와 ex_b는 1*1 행렬이므로 
# 그대로 사용해 행렬을 만들면 행렬 속 행렬인 셈이므로 이를 값(스칼라)으로 
# 바꿔야 한다. numpy.asscalar() 함수는 1*1 행렬을 스칼라 값으로 변환해준다.
ex_ab = np.matrix( [
                    [ (ex_a.item()), (ex_b.item()) ]
] )

# 투자 비중 * 주식 기대수익률이라는 행렬 연산을 한다. 
# 다만 둘 다 1*2 행렬이므로 ex_ab의 행렬을 전치(ex_ab.T) 해 행렬 곱을 계산한다.
ex_p = weight * ex_ab.T
print( '포트폴리오의 기대수익률은 %.2f%%' % ex_p)

주식 A의 기대수익률은 4.00%
주식 B의 기대수익률은 4.00%
포트폴리오의 기대수익률은 4.00%


In [11]:
# sqrt 함수를 사용하기 위해 math 모듈을 임포트 한다.
import math

# 경기 국면별 확률과 주식의 기대수익률
stock_a = [ 0.07, 0.04, 0.01 ]
stock_b = [ 0.13, 0.04, -0.05 ]
prob = [ 1/3, 1/3, 1/3 ]

# 주식 a와 b의 경기 국면에 따른 수익률 기댓값을 저장할 변수를 준비한다.
ex_a = 0.0
ex_b = 0.0

# 주식 a와 b의 기댓값을 구한다. 기대수익률 리스트와 
# 경기 국면별 확률 리스트를 곱한 합계를 구한다.
# 기대수익률과 경기 국면별 확률 리스트를 zip() 함수로 묶어 반복한다.
# (zip() 함수는 1.5.1절 참고). 그리고 그 결과 리스트의 값은 s와 p로 받고
# 둘을 곱한 합계를 계산한다.
for s, p in zip( stock_a, prob) : vex_a = ex_a + s*p

# 위의 두 줄 for 루프는 다음과 같이 한 줄의 인라인 for 루프로 바꿀 수 있다
ex_a = sum( s*p for s, p in zip( stock_a, prob) )

for s, p in zip( stock_b, prob ):
  ex_b = ex_b + s*p

# 위의 두 줄 for 루프틑 다음과 같이 한 줄의 인라인 for 루프로 바꿀 수 있다.
ex_b = sum( s*p for s, p in zip(stock_b, prob) )  

#분산을 저장할 변수와 투자 비중을 미리 준비한다.
var_a = 0.0
var_b = 0.0
wgt_a = 0.5
wgt_b = 0.5

# 위 코드 네 줄은 변수에 값을 할당하는 코드인데, 다음과 같이 한 줄로 
# 처리할 수 있다.
var_a, var_b, wgt_a, wgt_b = 0.0, 0.0, 0.5, 0.5

# 리스트 stock_a와 prob에서 각각 데이터를 변수 s와 p로 받아 반복한다.
# 확률과 편차 제곱을 곱해 var_a에 저장한다.
for s, p in zip( stock_a, prob ):
  var_a = var_a + p*( s-ex_a ) ** 2

# 위 반복문과 아래 반복문은 동일하다.
# var_a = sum( p*( s-ex_a ) ** 2 for s, p in zip( stock_a, prob ) )  

# 리스트 stock_b와 prob에서 각각 데이터를 변수 s와 p로 받아 반복한다.
# 확률과 편차제곱을 곱해 var_b에 저장한다.
for s, p in zip( stock_b, prob ):
  var_b = var_b + p*(s-ex_b)**2


# 위 반복문과 아래 반복문은 동일하다.
# var_b = sum( p*( s-ex_b ) ** 2 for s, p in zip( stock_b, prob ) )  

# 결과를 출력한다.
print( '주식 A의 분산은 {:.2%}'.format( var_a ) )
print( '주식 B의 분산은 {:.2%}'.format( var_b ) )

# 포트폴리오의 분산을 계산한다.
# 공분산, 분산, 표준편차를 계산한다.
cov = sum( p* ( a-ex_a ) * ( b-ex_b ) for a,b,p in zip( stock_a, stock_b, prob ) )
var_p = wgt_a ** 2 * var_a + wgt_b ** 2 * var_b + 2 * wgt_a * wgt_b * cov
std_p = math.sqrt( var_p )
print( '포트폴리오의 분산은 {:.2%}'.format( var_p ) )
print( '포트폴리오의 표준편차는 {:.2%}'.format( std_p ) )

주식 A의 분산은 0.06%
주식 B의 분산은 0.54%
포트폴리오의 분산은 0.24%
포트폴리오의 표준편차는 4.90%


In [12]:
# 포트폴리오의 분산을 계산한다.
# 공분산, 분산, 표준편차를 계산한다.
cov = sum( p*( a-ex_a ) * ( b*ex_b ) for a, b, p in zip( stock_a, stock_b, prob ) )
var_p = wgt_a **2 * var_a + wgt_b ** 2 * var_b + 2 * wgt_a * wgt_b * cov
std_p = math.sqrt( var_p )
print( '포트폴리오의 분산은 {:.2%}'.format( var_p ) )
print( '포트폴리오의 표준편차는 {:.2%}'.format( std_p ) )

# numpy.random.rand 함수로 10*1 난수 행렬을 만드는 예
import numpy as np

rnd = np.random.rand( 10 )
print( rnd ) 

# numpy.random.randn 함수로 3*10 난수 행렬을 만드는 예
import numpy as np
rnd = np.random.randn( 3, 10 )
print(rnd)

# 포트폴리오의 기대수익률 계산 
# numpy 라이브러리를 np라는 이름으로 임포트한다.
import numpy as np

# 자산의 개수를 정한다. 자산의 개수는 난수를 만들 때 사용할 것이다.
numStocks = 3

# 세 가지 경기 국면별로 자산의 개수만큼 주식의 수익률을 난수로 생성한다.
# [3 * numStocks] 배열을 만들고 만들어진 수익률 배열을 출력한다.
returns = np.random.randn( 3, numStocks )
print( '1. 난수로 만드는 국면별 주식의 수익률: \n', returns )

# 세 가지 경기 국면별 확률을 만든다. 이것 역시 난수로 만든다.
# 세 가지 국면의 확률의 전체 합이 1.0이 되도록 한다
# 난수를 세 개 만든다.
prob = np.random.rand( 3 )

#생성한 난수를 세 개 만든다.
prob = np.random.rand( 3 )

#생성한 난수를 난수의 합계로 나눠 합이 1.0이 되도록 한다.
prob = prob / prob.sum()
print( '2. 경기 국면별 각 확률: \n', prob )

# 경기 국면별 확률과 수익률을 행렬 곱셈한다. 
# 연산의 결과 각 주식의 기대 수익률이 계산된다.
# 경기 국면 별 확률과 수익률을 곱한다.
expectedReturns = np.matmul( prob.T, returns )

# prob.T는 prob 전치행렬이며 
# 두 행렬의 곱은 * 또는 matmul() 함수를 사용할 수 있다.
expectedReturns = prob.T * returns
print( '3. 각 주식의 기대수익률: \n', expectedReturns )

# 투자 비중을 만든다. 주식의 개수(numStocks)대로 난수를 만든 후 이를 
# 난수의 합으로 다시 나눠 전체 투자 비중의 합(100%)이 되도록 한다.
weights = np.random.rand( numStocks )
weights = weights / weights.sum( )
print( '4. 투자 비중 * 기대수익률: \n', weights)

# 각각의 투자 비중과 주식 기대수익률의 곱을 모두 합해 
# 포트폴리오의 기대 수익률을 계산한다.
expectedReturnOfPortfolio = np.sum( weights*expectedReturns )
print( '5. 포트폴리오의 기대수익률: {:.2%}'.format(expectedReturnOfPortfolio ) )

포트폴리오의 분산은 0.15%
포트폴리오의 표준편차는 3.92%
[0.88250103 0.18394742 0.54184272 0.81225601 0.7737831  0.10337616
 0.28802647 0.1243144  0.09310944 0.57164146]
[[-0.70739036 -2.17642407  0.18038645 -0.60586621  1.0077822  -0.30363123
   0.63594015  0.14868734  0.49032331  0.214253  ]
 [-0.74642635  0.48063814 -0.18470819 -2.37571072 -0.03018919 -1.19775607
   0.68579175  0.29799915  1.05193804  0.83473367]
 [-1.0377185  -0.76232087 -0.08095185  1.10703141  0.92741959 -0.32497574
   0.34278939 -0.72387337 -1.00437383 -0.63594604]]
1. 난수로 만드는 국면별 주식의 수익률: 
 [[-0.50711776  0.71973813  0.1904534 ]
 [-0.6385039  -0.24332435  1.18932265]
 [ 0.49594029  0.04555965  1.14102115]]
2. 경기 국면별 각 확률: 
 [0.59835007 0.13579735 0.26585258]
3. 각 주식의 기대수익률: 
 [[-0.30343395  0.09773853  0.05063253]
 [-0.38204885 -0.0330428   0.3161845 ]
 [ 0.29674591  0.00618688  0.30334342]]
4. 투자 비중 * 기대수익률: 
 [0.3503683  0.37815827 0.27147343]
5. 포트폴리오의 기대수익률: 7.25%


In [34]:
# 실제 미국 주식 데이터를 이용한 포트폴리오 기대수익률
# 필요한 라이브러리를 임포트한다.
import numpy as np
import pandas as pd
from pandas_datareader import data as web
import random

# 몇 가지 종목 코드(ticker)를 갖고 포트폴리오에 포함된 주식 리스트를 만든다.
tickers = [ 'MMM', 'ADBE', 'AMD', 'GOOGL', 'GOOG', 'AMZN']

# 수정주가를 담을 빈 데이터프레임을 미리 준비한다.
adjClose = pd.DataFrame()

# for 루프를 만들어 tickers 리스트를 반복하면서 종목 코드를 꺼내고 
# DataReader 함수를 사용해 수정주가 데이터를 내려받는다.
# 데이터는 야후 파이낸스를 통해 얻는다.
for item in tickers:
  adjClose[ item ] = web.DataReader( item, data_source = 'yahoo', start='15-09-2018' )[ 'Adj Close' ]

# pandas의 pct_change 함수는 데이터의 변화량을 %로 계산한다.
# 일간 수정주가 데이터를 일간수익률로 변환해 dailySimpleReturns에 저장한다.
dailySimpleReturns = adjClose.pct_change()

# 기대수익률 대신 일간수익률의 평균을 조사한다.
# 계산 결과는 np.matrix() 함수를 사용해 행렬로 변환 후 행렬 연산에 사용한다.
meanReturns = np.matrix( dailySimpleReturns.mean())

# 일간수익률을 연간수익률로 환산하기
annualReturns = dailySimpleReturns.mean() * 250

# 주식의 갯수만큼 투자 비중을 만든다.
numAssets = len( tickers )

# 투자 비중은 난수로 만들고 투자 비중을 비중의 합으로 나눠
# 투자 비중의 1.0이 되도록 만든다.
weights = np.random.random( numAssets )
weights = weights / sum( weights )

# 투자 비중과 연간 환산수익률을 곱해 포트폴리오 기대수익률을 계산한다.
# weights와 meanReturns의 차원은 1*6이다.
# 행렬의 곱셈 연산을 위해 meanReturns 행렬을 전치한다(meanReturns.T)
portReturnsExpected = np.sum( weights * meanReturns.T )

In [36]:
# n개 주식 포트폴리오의 분산을 계산하는 코드
# 다음 코드는 앞서 기대수익률을 계산하면서 이미 사용한 코드이므로 설명을 생략한다.
import numpy as np
import pandas as pd
from pandas_datareader import data as web
import random

tickers = [ 'MMM', 'ADBE', 'AMD', 'GOOGL', 'GOOG', 'AMZN']
adjClose = pd.DataFrame()

for item in tickers:
  adjClose[ item ] = web.DataReader( item, data_source = 'yahoo', start='15-09-2018' )[ 'Adj Close' ]
dailySimpleReturns = adjClose.pct_change()

# 행렬 연산을 위해 weights를 matrix 데이터형으로 변환한다.
weights = np.matrix( weights )

# dailySimpleReturns는 pandas의 DataFrame 객체다. 데이터형을 확인하기 위해
# type() 함수를 사용했다.
print( 'dailySimpleReturns의 데이터형: ', type( dailySimpleReturns ) )

# DataFrame 객체는 공분산을 계산해주는 cov 함수를 제공한다.
# cov 함수는 DataFrame을 돌려준다. 이번에도 데이터형을 확인하기 위해 
# type() 함수를 사용했다.
print( 'dailySimpleReturns.cov() 결과의 데이터형: ', type(dailySimpleReturns.cov() ) )

# cov() 함수로 공분산한 결과는 DataFrame이다. 
# 이 결과는 다시 행렬 연산을 위해 변환할 것이다.
# 그러므로 별도의 변수로 저장하지 않고 바로  values 함수를 사용해 행렬로 
# 변환하고 이를 pcov 변수로 저장한다.
pcov = dailySimpleReturns.cov().values

# 행렬 연산으로 분산을 계산한다. 즉, [비중 * 공분산 행렬 * 비중의 전치행렬]의
# 연산을 수행해 포트폴리오의 분산을 varp 변수에 저장하고 출력한다.
varp = weights * pcov * weights.T
print( '포트폴리오 분산은 ', varp)

dailySimpleReturns의 데이터형:  <class 'pandas.core.frame.DataFrame'>
dailySimpleReturns.cov() 결과의 데이터형:  <class 'pandas.core.frame.DataFrame'>
포트폴리오 분산은  [[0.00039543]]
